default: &default
  adapter: sqlite3
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  timeout: 5000

development:
  <<: *default
  database: storage/boc-hord-development.sqlite3

test:
  <<: *default
  database: storage/boc-hord-test.sqlite3

production:
  <<: *default
  # database: storage/boc-hord-production.sqlite3
